version: "3.8"

services:
  db:
    image: postgres:16
    container_name: go_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: go_api
    restart: always
    ports:
      - "8080:8081"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: goapi
      DB_PORT: 5432
      JWT_SECRET: 456546b5565465465465465
    volumes:
      - uploads:/app/uploads

volumes:
  pgdata:
  uploads:
